readerConfig.connectOptions.host = ${POSTGRES_HOST}
readerConfig.connectOptions.port = 5432
readerConfig.connectOptions.database = "flockr"
readerConfig.connectOptions.user = ${POSTGRES_USER}
readerConfig.connectOptions.password = ${POSTGRES_PASSWORD}
readerConfig.connectOptions.metricsName = "flockr.Postgres"
readerConfig.connectOptions.connectTimeout = 2000
readerConfig.connectOptions.useAffectedRows = true
readerConfig.connectOptions.cachePreparedStatements = true
readerConfig.poolOptions.maxSize = 5
readerConfig.poolOptions.maxWaitQueueSize = 2000
readerConfig.retryCount = 3

writerConfig.connectOptions.host =  ${POSTGRES_HOST}
writerConfig.connectOptions.port = 5432
writerConfig.connectOptions.database = "flockr"
writerConfig.connectOptions.user = ${POSTGRES_USER}
writerConfig.connectOptions.password = ${POSTGRES_PASSWORD}
writerConfig.connectOptions.metricsName = "flockr.Postgres"
writerConfig.connectOptions.connectTimeout = 2000
writerConfig.connectOptions.useAffectedRows = true
writerConfig.connectOptions.cachePreparedStatements = true
writerConfig.poolOptions.maxSize = 3
writerConfig.poolOptions.maxWaitQueueSize = 2000
writerConfig.retryCount = 3
