"executeRuleHandler" = {
    "schedulerKey" = "executeRuleHandler"
    "periodicDelayMs" = "5000"
    "minExecutionDelay" = "10"
}

"reconcileJobHandler" = {
    "schedulerKey" = "reconcileJobHandler"
    "periodicDelayMs" = "60000"
    "minExecutionDelay" = "60"
}
