app.name = "Flocker Spark Engine"

# S3A/Hadoop FS configurations
s3a.multipart.purge.age = "86400000"
s3a.connection.timeout = "60000"
s3a.connection.establish.timeout = "60000"
s3a.connection.request.timeout = "60000"
s3a.threads.keepalivetime = "60"

# Spark SQL configurations
sql.shuffle.partitions = "200"
sql.adaptive.enabled = true
sql.adaptive.coalescePartitions.enabled = true

# Network configurations
network.timeout = "300s"

