host="aerospike"
eventLoopSize=16
maxCommandsInProcess=40
maxConnectionsPerNode=700
maxCommandsInQueue=0

namespace="test"
cohortCreatedAtBin="createdAtMap"
cohortUpdatedAtBin="updatedAtMap"
cohortExpiryBin="expiryMap"