host="localhost"
eventLoopSize=16
maxCommandsInProcess=40
maxConnectionsPerNode=700
maxCommandsInQueue=0

namespace="user-cohorts"
persistentCohortsSet="persistent-cohorts"
cohortCreatedAtBin="createdAtMap"
cohortUpdatedAtBin="updatedAtMap"
cohortExpiryBin="expiryMap"