<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ascend</groupId>
        <artifactId>flockr</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>flockr-users</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Main class and verticle for this module -->
        <main.class>io.ascend.flockr.users.MainLauncher</main.class>
        <main.verticle>io.ascend.flockr.users.verticle.MainVerticle</main.verticle>

        <!-- Swagger configuration for this module -->
        <swagger.configurationFilePath>
            ${project.basedir}/src/main/resources/config/swagger/swagger-info.json
        </swagger.configurationFilePath>
        <swagger.outputFileName>flockr-users</swagger.outputFileName>
        <swagger.outputPath>
            ${project.basedir}/src/main/resources/webroot/swagger
        </swagger.outputPath>
        <swagger.resourcePackage>io.ascend.flockr.users.controller</swagger.resourcePackage>

        <!-- Aerospike versions -->
        <aerospike.version>6.2.0</aerospike.version>
        <vertx-aerospike.version>2.0.1</vertx-aerospike.version>
    </properties>

    <dependencies>
        <!-- Aerospike Client -->
        <dependency>
            <groupId>com.aerospike</groupId>
            <artifactId>aerospike-client</artifactId>
            <version>${aerospike.version}</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>${logback.version}</version>
        </dependency>

        <!-- Vert.x Aerospike Client -->
        <dependency>
            <groupId>io.d11</groupId>
            <artifactId>vertx-aerospike-client</artifactId>
            <version>${vertx-aerospike.version}</version>
        </dependency>

        <!-- RESTEasy multipart provider -->
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-multipart-provider</artifactId>
            <version>${resteasy.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Enable Swagger generation for this module using parent pluginManagement config -->
            <plugin>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-maven-plugin-jakarta</artifactId>
            </plugin>
        </plugins>
    </build>

</project>