<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ascend</groupId>
        <artifactId>flockr</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>flockr-users</artifactId>

    <properties>
        <maven.compiler.source>23</maven.compiler.source>
        <maven.compiler.target>23</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Main class and verticle for this module -->
        <main.class>io.ascend.flockr.users.Main</main.class>
        <main.verticle>io.ascend.flockr.users.verticle.MainVerticle</main.verticle>

        <!-- Swagger configuration for this module -->
        <swagger.configurationFilePath>
            ${project.basedir}/src/main/resources/config/swagger/swagger-info.json
        </swagger.configurationFilePath>
        <swagger.outputFileName>flockr-users</swagger.outputFileName>
        <swagger.outputPath>
            ${project.basedir}/src/main/resources/webroot/swagger
        </swagger.outputPath>
        <swagger.resourcePackage>io.ascend.flockr.users</swagger.resourcePackage>
    </properties>

    <build>
        <plugins>
            <!-- Enable Swagger generation for this module using parent pluginManagement config -->
            <plugin>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-maven-plugin-jakarta</artifactId>
            </plugin>
        </plugins>
    </build>

</project>